"""Adicionada coluna paciente_id no exame

Revision ID: 187e812f34f2
Revises: 4a7a84d3ce95
Create Date: 2022-02-09 22:56:20.495648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187e812f34f2'
down_revision = '4a7a84d3ce95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exames', sa.Column('Paciente_ID', sa.String(), nullable=True))
    op.create_foreign_key(None, 'exames', 'pacientes', ['Paciente_ID'], ['Paciente_ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exames', type_='foreignkey')
    op.drop_column('exames', 'Paciente_ID')
    # ### end Alembic commands ###
