"""AdicionadaTabelaReceita

Revision ID: 26fc7ec6027e
Revises: 71e7411435a5
Create Date: 2022-01-17 23:42:43.969731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fc7ec6027e'
down_revision = '71e7411435a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receitas',
    sa.Column('Receita_ID', sa.String(), nullable=False),
    sa.Column('Data', sa.DateTime(), nullable=True),
    sa.Column('Nome_Arquivo', sa.String(), nullable=True),
    sa.Column('Consulta_ID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Consulta_ID'], ['consultas.Consulta_ID'], ),
    sa.PrimaryKeyConstraint('Receita_ID')
    )
    op.create_index(op.f('ix_receitas_Receita_ID'), 'receitas', ['Receita_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receitas_Receita_ID'), table_name='receitas')
    op.drop_table('receitas')
    # ### end Alembic commands ###
