"""InitialCreation

Revision ID: 71e7411435a5
Revises: 
Create Date: 2022-01-17 21:22:56.797522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e7411435a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoriasExame',
    sa.Column('CategoriaExame_ID', sa.String(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CategoriaExame_ID')
    )
    op.create_index(op.f('ix_categoriasExame_CategoriaExame_ID'), 'categoriasExame', ['CategoriaExame_ID'], unique=False)
    op.create_table('especialidades',
    sa.Column('Especialidade_ID', sa.String(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Especialidade_ID'),
    sa.UniqueConstraint('Nome')
    )
    op.create_index(op.f('ix_especialidades_Especialidade_ID'), 'especialidades', ['Especialidade_ID'], unique=False)
    op.create_table('medicos',
    sa.Column('Medico_ID', sa.String(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=True),
    sa.Column('CPF', sa.String(), nullable=True),
    sa.Column('CRM', sa.String(), nullable=True),
    sa.Column('Cidade', sa.String(), nullable=True),
    sa.Column('Estado', sa.String(), nullable=True),
    sa.Column('Logradouro', sa.String(), nullable=True),
    sa.Column('Logradouro_Numero', sa.String(), nullable=True),
    sa.Column('CEP', sa.String(), nullable=True),
    sa.Column('Telefone', sa.String(), nullable=True),
    sa.Column('Celular', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Descricao', sa.String(), nullable=True),
    sa.Column('Sexo', sa.CHAR(), nullable=True),
    sa.Column('Data_Nascimento', sa.Date(), nullable=True),
    sa.Column('Senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Medico_ID')
    )
    op.create_index(op.f('ix_medicos_Medico_ID'), 'medicos', ['Medico_ID'], unique=False)
    op.create_table('pacientes',
    sa.Column('Paciente_ID', sa.String(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=True),
    sa.Column('Data_Nascimento', sa.Date(), nullable=True),
    sa.Column('CPF', sa.String(), nullable=True),
    sa.Column('Cidade', sa.String(), nullable=True),
    sa.Column('Estado', sa.String(), nullable=True),
    sa.Column('Logradouro', sa.String(), nullable=True),
    sa.Column('Logradouro_Numero', sa.Integer(), nullable=True),
    sa.Column('CEP', sa.String(), nullable=True),
    sa.Column('Telefone', sa.String(), nullable=True),
    sa.Column('Celular', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Paciente_ID')
    )
    op.create_index(op.f('ix_pacientes_Paciente_ID'), 'pacientes', ['Paciente_ID'], unique=False)
    op.create_table('exames',
    sa.Column('Exame_ID', sa.String(), nullable=False),
    sa.Column('Data', sa.DateTime(), nullable=True),
    sa.Column('Nome_Arquivo', sa.String(), nullable=True),
    sa.Column('CategoriaExame_ID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CategoriaExame_ID'], ['categoriasExame.CategoriaExame_ID'], ),
    sa.PrimaryKeyConstraint('Exame_ID')
    )
    op.create_index(op.f('ix_exames_Exame_ID'), 'exames', ['Exame_ID'], unique=False)
    op.create_table('horarios',
    sa.Column('Horario_ID', sa.String(), nullable=False),
    sa.Column('Data', sa.Date(), nullable=True),
    sa.Column('Horario_Inicio', sa.Time(), nullable=True),
    sa.Column('Horario_Fim', sa.Time(), nullable=True),
    sa.Column('Medico_ID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Medico_ID'], ['medicos.Medico_ID'], ),
    sa.PrimaryKeyConstraint('Horario_ID')
    )
    op.create_index(op.f('ix_horarios_Horario_ID'), 'horarios', ['Horario_ID'], unique=False)
    op.create_table('medicoEspecialidade',
    sa.Column('MedicoEspecialidade_ID', sa.String(), nullable=False),
    sa.Column('Medico_ID', sa.String(), nullable=True),
    sa.Column('Especialidade_ID', sa.String(), nullable=True),
    sa.Column('ModeloAnamnese', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Especialidade_ID'], ['especialidades.Especialidade_ID'], ),
    sa.ForeignKeyConstraint(['Medico_ID'], ['medicos.Medico_ID'], ),
    sa.PrimaryKeyConstraint('MedicoEspecialidade_ID')
    )
    op.create_index(op.f('ix_medicoEspecialidade_MedicoEspecialidade_ID'), 'medicoEspecialidade', ['MedicoEspecialidade_ID'], unique=False)
    op.create_table('consultas',
    sa.Column('Consulta_ID', sa.String(), nullable=False),
    sa.Column('Anamnese', sa.String(), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('Paciente_ID', sa.String(), nullable=True),
    sa.Column('Medico_ID', sa.String(), nullable=True),
    sa.Column('Horario_ID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Horario_ID'], ['horarios.Horario_ID'], ),
    sa.ForeignKeyConstraint(['Medico_ID'], ['medicos.Medico_ID'], ),
    sa.ForeignKeyConstraint(['Paciente_ID'], ['pacientes.Paciente_ID'], ),
    sa.PrimaryKeyConstraint('Consulta_ID')
    )
    op.create_index(op.f('ix_consultas_Consulta_ID'), 'consultas', ['Consulta_ID'], unique=False)
    op.create_table('exameConsulta',
    sa.Column('ExameConsulta_ID', sa.String(), nullable=False),
    sa.Column('Consulta_ID', sa.String(), nullable=True),
    sa.Column('Exame_ID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Consulta_ID'], ['consultas.Consulta_ID'], ),
    sa.ForeignKeyConstraint(['Exame_ID'], ['exames.Exame_ID'], ),
    sa.PrimaryKeyConstraint('ExameConsulta_ID')
    )
    op.create_index(op.f('ix_exameConsulta_ExameConsulta_ID'), 'exameConsulta', ['ExameConsulta_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exameConsulta_ExameConsulta_ID'), table_name='exameConsulta')
    op.drop_table('exameConsulta')
    op.drop_index(op.f('ix_consultas_Consulta_ID'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_medicoEspecialidade_MedicoEspecialidade_ID'), table_name='medicoEspecialidade')
    op.drop_table('medicoEspecialidade')
    op.drop_index(op.f('ix_horarios_Horario_ID'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_exames_Exame_ID'), table_name='exames')
    op.drop_table('exames')
    op.drop_index(op.f('ix_pacientes_Paciente_ID'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_medicos_Medico_ID'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_especialidades_Especialidade_ID'), table_name='especialidades')
    op.drop_table('especialidades')
    op.drop_index(op.f('ix_categoriasExame_CategoriaExame_ID'), table_name='categoriasExame')
    op.drop_table('categoriasExame')
    # ### end Alembic commands ###
