"""Adicionada coluna linkmeet na consulta

Revision ID: 7575d4179aac
Revises: 187e812f34f2
Create Date: 2022-02-11 20:07:57.187321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7575d4179aac'
down_revision = '187e812f34f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('LinkMeet', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultas', 'LinkMeet')
    # ### end Alembic commands ###
