# -*- coding: utf-8 -*-
"""AnalisesTweets_AntesDeClassificar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aUbohWZy6xw5ZAiBUHT8Oc_QSLkrWAXM
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from wordcloud import ImageColorGenerator
from wordcloud import STOPWORDS
from sklearn.feature_extraction import text
import numpy as np
from PIL import Image

df_bolsonaro = pd.read_csv('extracoes/extracao_28_09_bolsonaro.csv', index_col=0)

df_lula = pd.read_csv('extracoes/extracao_28_09_lula.csv', index_col=0)

df_ciro = pd.read_csv('extracoes/extracao_28_09_ciro.csv', index_col=0)

df_simone = pd.read_csv('extracoes/extracao_28_09_simone.csv', index_col=0)

dias = sorted(df_bolsonaro['Data_post'].str[:10].unique())

cont1=[]
cont2=[]
cont3=[]
cont4=[]

for dia in dias:
    cont1.append(len(df_bolsonaro[df_bolsonaro['Data_post'].str[:10]==dia]))
    cont2.append(len(df_lula[df_lula['Data_post'].str[:10]==dia]))
    cont3.append(len(df_simone[df_simone['Data_post'].str[:10]==dia]))
    cont4.append(len(df_ciro[df_ciro['Data_post'].str[:10]==dia]))

df_cont_dias = pd.DataFrame(data={'bolsonaro': cont1,
                   'lula': cont2,
                  'simone': cont3,
                  'ciro': cont4}, index=dias)

df_cont_dias

df_cont_dias.plot( kind="bar", figsize=(15, 10), color=['#44bd32','#AF0016','#A4059F','#273c75'])
 
# print bar graph
plt.show()

horarios = sorted(df_bolsonaro['Data_post'].str[:13].unique())
cont1=[]
cont2=[]
cont3=[]
cont4=[]

for horario in horarios:
    cont1.append(len(df_bolsonaro[df_bolsonaro['Data_post'].str[:13]==horario]))
    cont2.append(len(df_lula[df_lula['Data_post'].str[:13]==horario]))
    cont3.append(len(df_simone[df_simone['Data_post'].str[:13]==horario]))
    cont4.append(len(df_ciro[df_ciro['Data_post'].str[:13]==horario]))
df_cont_horarios = pd.DataFrame(data={'bolsonaro': cont1,
                   'lula': cont2,
                  'simone': cont3,
                  'ciro': cont4}, index=horarios)

df_cont_horarios.index = df_cont_horarios.index.str[5:]

df_cont_horarios.plot( figsize=(15, 10), color=['#44bd32','#AF0016','#A4059F','#273c75'],marker='o', fontsize=16)
plt.xticks(range(0,len(df_cont_horarios.index),22), df_cont_horarios.index.str[:5].unique())
plt.show()

text = " ".join(i for i in df_simone.Texto)
mask = np.array(Image.open("3.PNG"))
#stop = set(stopwords.words("portuguese")+['rt','RT','tô','tá','https','http','vc', 'hithheld'])
wordcloud = WordCloud(stopwords=stop, background_color="white", mode="RGBA", max_words=1000, mask=mask).generate(text)
image_colors = ImageColorGenerator(mask)
plt.figure( figsize=[20,20])
plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.savefig("Simone_Cloud.png", format="png")
plt.show()

text = " ".join(i for i in df_bolsonaro.Texto)
mask = np.array(Image.open("1.PNG"))
#stop = set(stopwords.words("portuguese")+['rt','RT','tô','tá','https','http','vc', 'hithheld'])
wordcloud = WordCloud(stopwords=stop, background_color="white", mode="RGBA", max_words=1000, mask=mask).generate(text)
image_colors = ImageColorGenerator(mask)
plt.figure( figsize=[20,20])
plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.savefig("Bolsonaro_Cloud.png", format="png")
plt.show()

text = " ".join(i for i in df_ciro.Texto)
mask = np.array(Image.open("4.PNG"))
#stop = set(stopwords.words("portuguese")+['rt','RT','tô','tá','https','http','vc', 'hithheld'])
wordcloud = WordCloud(stopwords=stop, background_color="white", mode="RGBA", max_words=1000, mask=mask).generate(text)
image_colors = ImageColorGenerator(mask)
plt.figure( figsize=[20,20])
plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.savefig("Ciro_Cloud.png", format="png")
plt.show()

text = " ".join(i for i in df_lula.Texto)
mask = np.array(Image.open("2.PNG"))
#stop = set(stopwords.words("portuguese")+['rt','RT','tô','tá','https','http','vc', 'hithheld'])
wordcloud = WordCloud(stopwords=stop, background_color="white", mode="RGBA", max_words=1000, mask=mask).generate(text)
image_colors = ImageColorGenerator(mask)
plt.figure( figsize=[20,20])
plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.savefig("Lula_Cloud.png", format="png")
plt.show()

df_todos = df_bolsonaro.append(df_lula)
df_todos = df_todos.append(df_simone)
df_todos = df_todos.append(df_ciro)
df_todos = df_todos.drop_duplicates()

text = " ".join(i for i in df_todos.Texto)
wordcloud = WordCloud(stopwords=stop, background_color="white").generate(text)
plt.figure( figsize=(15,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

df_lula.Texto.str.extractall(r'(\#\w+)')[0].value_counts()

df_bolsonaro.Texto.str.extractall(r'(\#\w+)')[0].value_counts()

df_simone.Texto.str.extractall(r'(\#\w+)')[0].value_counts()

df_ciro.Texto.str.extractall(r'(\#\w+)')[0].value_counts()

hashtags = df_todos.Texto.str.extractall(r'(\#\w+)')[0].value_counts()
hashtags

hashtags_lula = df_lula.Texto.str.extractall(r'(\#\w+)')[0].value_counts()
hashtags_lula[:50]

hashtags_bolsonaro = df_bolsonaro.Texto.str.extractall(r'(\#\w+)')[0].value_counts()
hashtags_bolsonaro[:50]

hashtags_simone = df_simone.Texto.str.extractall(r'(\#\w+)')[0].value_counts()
hashtags_simone[:50]

hashtags_simone

hashtags_ciro = df_ciro.Texto.str.extractall(r'(\#\w+)')[0].value_counts()
hashtags_ciro[:50]

text = " ".join(i for i in df_todos.Texto.str.extractall(r'(\#\w+)')[0])
wordcloud = WordCloud( background_color="white").generate(text)
plt.figure( figsize=(15,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()