# -*- coding: utf-8 -*-
"""AumentoClassificacaoManual.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vn5oUGYWp8asDKRTho5dG9WC1DIwIV-1
"""

import pandas as pd

df_bolsonaro = pd.read_excel('Classificar_x_p_n_novo.xlsx', index_col=0,sheet_name='Bolsonaro')  
df_lula = pd.read_excel('Classificar_x_p_n_novo.xlsx', index_col=0,sheet_name='Lula') 
df_simone = pd.read_excel('Classificar_x_p_n_novo.xlsx', index_col=0,sheet_name='Simone') 
df_ciro = pd.read_excel('Classificar_x_p_n_novo.xlsx', index_col=0,sheet_name='Ciro')

df_bolsonaro = df_bolsonaro.reset_index()
df_lula = df_lula.reset_index()
df_simone = df_simone.reset_index()
df_ciro = df_ciro.reset_index()

for i in df_lula[(df_lula['Sentimento'].isna())&
        ((df_lula['Texto'].str.contains('LulaArregou'))|
          (df_lula['Texto'].str.contains('LulaLadraoSeuLugarENaPrisao'))|
          (df_lula['Texto'].str.contains('LulaArregao'))|
         (df_lula['Texto'].str.contains('PTNuncaMais'))|
         (df_lula['Texto'].str.contains('Lula ladrão')))
         
         ].index:
    df_lula.loc[i,'Sentimento']='n'

for i in df_lula[(df_lula['Sentimento'].isna())&
        ((df_lula['Texto'].str.contains('LulaNo1ºTurno'))|
          (df_lula['Texto'].str.contains('LulaPresidente13'))|
          (df_lula['Texto'].str.contains('LulaNoPrimeiroTurno'))|
         (df_lula['Texto'].str.contains('LulaNoPrimeiroTurno13'))|
          (df_lula['Texto'].str.contains('LulaEoPTtudoNoPrimeiroTurno'))|
          (df_lula['Texto'].str.contains('Vote13'))|
         (df_lula['Texto'].str.contains('LulaPresidente'))|
          (df_lula['Texto'].str.contains('LulaPeloBrasilHaddadPorSP'))|
          (df_lula['Texto'].str.contains('lula2022'))|
          (df_lula['Texto'].str.contains('LulaEoPTaVerdadeVencerá'))|
          (df_lula['Texto'].str.contains('LulaNo1oturno'))|
          (df_lula['Texto'].str.contains('Lula13Presidente'))|
          (df_lula['Texto'].str.contains('LulaEoPTaVerdadeVencera'))|
          (df_lula['Texto'].str.contains('LulaPeloBrasilHaddadPorSP'))|
          (df_lula['Texto'].str.contains('LulaPeloBrasilHaddadPorSP')))
         
         ].index:
    df_lula.loc[i,'Sentimento']='p'

df_lula[(~df_lula['Sentimento'].isna()) & (df_lula['Sentimento']!=' ')]['Sentimento'].value_counts()

df_lula.loc[df_lula[df_lula['Sentimento']=='N'].index,'Sentimento']='n'
df_lula.loc[df_lula[df_lula['Sentimento']=='P'].index,'Sentimento']='p'
df_lula.loc[df_lula[df_lula['Sentimento']=='P '].index,'Sentimento']='p'
df_lula[(~df_lula['Sentimento'].isna()) & (df_lula['Sentimento']!=' ')]['Sentimento'].value_counts()

df_lula.to_excel('Classificar_x_p_n_lula2.xlsx')

df_bolsonaro = pd.read_excel('Classificar_x_p_n_novo.xlsx', index_col=0,sheet_name='Bolsonaro')

df_bolsonaro = df_bolsonaro.reset_index()

for i in df_bolsonaro[(df_bolsonaro['Sentimento'].isna())&
        ((df_bolsonaro['Texto'].str.contains('BolsonaroNoPrimeiroTurno'))|
          (df_bolsonaro['Texto'].str.contains('Bolsonaro22'))|
          (df_bolsonaro['Texto'].str.contains('Vote22Bolsonaro'))|
         (df_bolsonaro['Texto'].str.contains('BolsonaroReeleitoEm2022'))|
          (df_bolsonaro['Texto'].str.contains('EuVotoBolsonaro22'))|
          (df_bolsonaro['Texto'].str.contains('BolsonaroReeleito'))|
         (df_bolsonaro['Texto'].str.contains('Bolsonaro2022'))|
          (df_bolsonaro['Texto'].str.contains('BolsonaroNoPrimeiroTurno22'))|
          (df_bolsonaro['Texto'].str.contains('Vote22'))|
          (df_bolsonaro['Texto'].str.contains('BolsonaroReeleito2022'))|
          (df_bolsonaro['Texto'].str.contains('VoteBolsonaro22'))|
          (df_bolsonaro['Texto'].str.contains('BrasilComBolsonaro22'))|
          (df_bolsonaro['Texto'].str.contains('BrasilVota22'))|
          (df_bolsonaro['Texto'].str.contains('BolsonaroReeleitoNoPrimeiroTurno'))|
          (df_bolsonaro['Texto'].str.contains('bolsonaro22')))
         
         ].index:
    df_bolsonaro.loc[i,'Sentimento']='p'

for i in df_bolsonaro[(df_bolsonaro['Sentimento'].isna())&
        ((df_bolsonaro['Texto'].str.contains('ForaBolsonaro'))|
          (df_bolsonaro['Texto'].str.contains('tchutchucaDoCentrao'))|
          (df_bolsonaro['Texto'].str.contains('bolsominion'))|
          (df_bolsonaro['Texto'].str.contains('Bolsominion')))
         
         ].index:
    df_bolsonaro.loc[i,'Sentimento']='n'

df_bolsonaro[~df_bolsonaro['Sentimento'].isna()]

df_bolsonaro2 = df_bolsonaro

df_bolsonaro = df_bolsonaro2

df_bolsonaro[(~df_bolsonaro['Sentimento'].isna()) & (df_bolsonaro['Sentimento']!=' ')]['Sentimento'].value_counts()

df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='N'].index,'Sentimento']='n'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='p '].index,'Sentimento']='p'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='n '].index,'Sentimento']='n'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='P'].index,'Sentimento']='p'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='\np'].index,'Sentimento']='p'
df_bolsonaro[(~df_bolsonaro['Sentimento'].isna()) & (df_bolsonaro['Sentimento']!=' ')]['Sentimento'].value_counts()

df_bolsonaro = df_bolsonaro.reset_index()

df_bolsonaro[df_bolsonaro['Sentimento']=='x ']

df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='x '].index,'Sentimento']='x'

df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='N'].index,'Sentimento']='n'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='p '].index,'Sentimento']='p'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='n '].index,'Sentimento']='n'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='x '].index,'Sentimento']='x'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='P'].index,'Sentimento']='p'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='X'].index,'Sentimento']='x'
df_bolsonaro.loc[df_bolsonaro[df_bolsonaro['Sentimento']=='\np'].index,'Sentimento']='p'

df_bolsonaro[(~df_bolsonaro['Sentimento'].isna()) & (df_bolsonaro['Sentimento']!=' ')]['Sentimento'].value_counts()

df_bolsonaro.to_excel('Classificar_x_p_n_bolsonaro2.xlsx')

for i in df_simone[(df_simone['Sentimento'].isna())&
        ((df_simone['Texto'].str.contains('SimonePresidente15'))|
          (df_simone['Texto'].str.contains('Simone15'))|
          (df_simone['Texto'].str.contains('SimonePresidente'))|
         (df_simone['Texto'].str.contains('Virada15'))|
          (df_simone['Texto'].str.contains('SouSimonePelaPaz'))|
          (df_simone['Texto'].str.contains('Simonetebet'))|
         (df_simone['Texto'].str.contains('Simonepresidente'))|
          (df_simone['Texto'].str.contains('elasim')))
         
         ].index:
    df_simone.loc[i,'Sentimento']='p'

df_simone.loc[df_simone[df_simone['Sentimento']=='N'].index,'Sentimento']='n'
df_simone.loc[df_simone[df_simone['Sentimento']=='p '].index,'Sentimento']='p'
df_simone.loc[df_simone[df_simone['Sentimento']=='n '].index,'Sentimento']='n'
df_simone.loc[df_simone[df_simone['Sentimento']=='x '].index,'Sentimento']='x'
df_simone.loc[df_simone[df_simone['Sentimento']=='P'].index,'Sentimento']='p'
df_simone.loc[df_simone[df_simone['Sentimento']=='X'].index,'Sentimento']='x'
df_simone.loc[df_simone[df_simone['Sentimento']=='\np'].index,'Sentimento']='p'

df_simone[(~df_simone['Sentimento'].isna()) & (df_simone['Sentimento']!=' ')]['Sentimento'].value_counts()

df_simone.to_excel('Classificar_x_p_n_simone2.xlsx')

for i in df_ciro[(df_ciro['Sentimento'].isna())&
        ((df_ciro['Texto'].str.contains('CiroPresidente12'))|
          (df_ciro['Texto'].str.contains('PrefiroCiro'))|
          (df_ciro['Texto'].str.contains('CiroContraOSistema'))|
         (df_ciro['Texto'].str.contains('PrefiroCiro12'))|
          (df_ciro['Texto'].str.contains('Ciro12'))|
          (df_ciro['Texto'].str.contains('VotaNoCiro'))|
         (df_ciro['Texto'].str.contains('CiroNoSegundoTurno'))|
          (df_ciro['Texto'].str.contains('PrefiroCiroPresidente12'))|
          (df_ciro['Texto'].str.contains('prefirociro'))|
          (df_ciro['Texto'].str.contains('CiroPresidente'))|
          (df_ciro['Texto'].str.contains('ComCiroAteOFim'))|
          (df_ciro['Texto'].str.contains('agoraéciro'))|
          (df_ciro['Texto'].str.contains('verdadeirovotoutil'))|
          (df_ciro['Texto'].str.contains('EstamosComCiroGomes')))
         
         ].index:
    df_ciro.loc[i,'Sentimento']='p'

df_ciro.loc[df_ciro[df_ciro['Sentimento']=='N'].index,'Sentimento']='n'
df_ciro.loc[df_ciro[df_ciro['Sentimento']=='p '].index,'Sentimento']='p'
df_ciro.loc[df_ciro[df_ciro['Sentimento']=='n '].index,'Sentimento']='n'
df_ciro.loc[df_ciro[df_ciro['Sentimento']=='x '].index,'Sentimento']='x'
df_ciro.loc[df_ciro[df_ciro['Sentimento']=='P'].index,'Sentimento']='p'
df_ciro.loc[df_ciro[df_ciro['Sentimento']=='X'].index,'Sentimento']='x'
df_ciro.loc[df_ciro[df_ciro['Sentimento']=='\np'].index,'Sentimento']='p'

df_ciro[(~df_ciro['Sentimento'].isna()) & (df_ciro['Sentimento']!=' ')]['Sentimento'].value_counts()

df_ciro.to_excel('Classificar_x_p_n_ciro2.xlsx')