# -*- coding: utf-8 -*-
"""Baixar_tweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FD7UMb9u3Fiwsc98nnjo3KKNP-pPUM6K
"""

import tweepy as tw
import pandas as pd
import time

lula = ' (lula OR PT eleic OR Luiz inacio OR Alckmin) '
bolsonaro = ' (bolsonaro OR PL eleic OR Braga Netto) '
ciro = ' (ciro OR PDT eleic OR Ana Paula Matos) '
simone = ' (Simone tebet OR MDB eleic OR Mara Gabrilli) '


query_eleicoes =lula + 'OR' +\
                bolsonaro + 'OR' +\
                ciro + 'OR' +\
                simone 

Querys = [lula, bolsonaro, ciro, simone]

query_eleicoes

consumer_key = "vaQ2K4ySd4eug4mFl1ccljzJT"

consumer_secret = "g6V151NbLv6CDF6HEXutjVuDQqcEIrHbiNq0iQAnvnbPMiDDMQ"

access_token = "290244168-dmkNwKj9lgDqMuz9LtC20LwanIRItKxiUo9GL1fz"

access_token_secret = "Wy9ekZE9sM5bNBDwyiZhgpD5QF5GqjE9nmEWXQKZGwWCm"

bearer_token = 'AAAAAAAAAAAAAAAAAAAAAOvQhgEAAAAAhqpFhqYK5oLuNFU5o5vMCXn9%2FYw%3D8ghu3rd3NcRooAUI9pd9JqPv4kha6dKbGSVwZUUpc4uQREf8tG'

# Criando nosso Client
cliente = tw.Client(bearer_token,consumer_key, consumer_secret, access_token, access_token_secret)

base = pd.DataFrame( columns=['Data_post', 'ID', 'Texto', 'Eh_RT'])
base

def tweets_for_df(dados, index, base):
    for i in dados:
        texto = i.text

        if (texto[:2] == 'RT'):
            RT = 'S'
        else:
            RT = 'N'
        base.loc[index,'Data_post']=inicio
        base.loc[index,'ID']=i.id
        base.loc[index,'Texto']=texto
        base.loc[index,'Eh_RT']=RT
        index+=1
        
    
    return base, index

indexLula = 0
indexBolsonaro = 0
indexCiro = 0
indexSimone = 0

baseLula = pd.DataFrame( columns=['Data_post', 'ID', 'Texto', 'Eh_RT'])
baseBolsonaro = pd.DataFrame( columns=['Data_post', 'ID', 'Texto', 'Eh_RT'])
baseCiro = pd.DataFrame( columns=['Data_post', 'ID', 'Texto', 'Eh_RT'])
baseSimone = pd.DataFrame( columns=['Data_post', 'ID', 'Texto', 'Eh_RT'])

ano = '2022-'
mes = '10-'
segundos = ':00Z'
dia =2
hora = 14
minuto= 59
while(True):
    if(minuto==59):
        minuto_fim = '0'
        if(hora==23):
            hora_fim = '0'
            dia_fim = str (dia+1)
        else:
            hora_fim = str (hora+1)
            dia_fim = str(dia)
    else:
        minuto_fim = str(minuto+1)
        hora_fim = str(hora)
        dia_fim = str (dia)

    if(dia<=9): dia_ini = '0' + str(dia)
    else: dia_ini = str(dia)

    if(minuto<=9): minuto_ini = '0' + str(minuto)
    else: minuto_ini = str(minuto)

    if(hora<=9): hora_ini = '0' + str(hora)
    else: hora_ini = str(hora)

    if(int(dia_fim)<=9): dia_fim = '0' + dia_fim

    if(int(minuto_fim)<=9): minuto_fim = '0' + minuto_fim

    if(int(hora_fim)<=9): hora_fim = '0' + hora_fim

    inicio = ano + mes + dia_ini + 'T' + hora_ini + ':' + minuto_ini + segundos
    fim = ano + mes + dia_fim + 'T' + hora_fim + ':' + minuto_fim + segundos
    print("inicio: "+inicio)
    print("fim: "+fim)
    print()
    
    
    
    resposta = cliente.search_recent_tweets(query=[(lula + 'lang:pt' )] ,
                                            max_results=100,
                                            start_time=inicio,
                                            end_time=fim)
    dados = resposta.data
    if dados is not None:
        baseLula, indexLula = tweets_for_df(dados, indexLula, baseLula)
    time.sleep(2)
    
    
    resposta = cliente.search_recent_tweets(query=[(bolsonaro + 'lang:pt' )] ,
                                            max_results=100,
                                            start_time=inicio,
                                            end_time=fim)
    dados = resposta.data
    if dados is not None:
        baseBolsonaro, indexBolsonaro = tweets_for_df(dados, indexBolsonaro, baseBolsonaro)
    time.sleep(2)
    
    
    resposta = cliente.search_recent_tweets(query=[(ciro + 'lang:pt' )] ,
                                            max_results=100,
                                            start_time=inicio,
                                            end_time=fim)
    dados = resposta.data
    if dados is not None:
        baseCiro, indexCiro = tweets_for_df(dados, indexCiro, baseCiro)
    time.sleep(2)
    
    
    resposta = cliente.search_recent_tweets(query=[(simone + 'lang:pt' )] ,
                                            max_results=100,
                                            start_time=inicio,
                                            end_time=fim)
    dados = resposta.data
    if dados is not None:
        baseSimone, indexSimone = tweets_for_df(dados, indexSimone, baseSimone)
    time.sleep(2)
    
    minuto-=1
    if(minuto==-1):
        minuto=59
        hora-=1
        if(hora==-1):
            hora=23
            
            baseLula= baseLula.drop_duplicates()
            baseBolsonaro= baseBolsonaro.drop_duplicates()
            baseCiro= baseCiro.drop_duplicates()
            baseSimone= baseSimone.drop_duplicates()
            baseLula.to_csv('extracoes/extracao_' +
                            str(dia)+"_"+
                            mes.replace("-", "_") + 
                            lula.split(" ", 2)[1].replace("(", "") + '.csv')
            baseBolsonaro.to_csv('extracoes/extracao_' +
                            str(dia)+"_"+
                            mes.replace("-", "_") + 
                            bolsonaro.split(" ", 2)[1].replace("(", "") + '.csv')
            baseCiro.to_csv('extracoes/extracao_' +
                            str(dia)+"_"+
                            mes.replace("-", "_") + 
                            ciro.split(" ", 2)[1].replace("(", "") + '.csv')
            baseSimone.to_csv('extracoes/extracao_' +
                            str(dia)+"_"+
                            mes.replace("-", "_") + 
                            simone.split(" ", 2)[1].replace("(", "") + '.csv')
            dia-=1
            if(dia==0):
                dia=30
                mes = '09-'

cliente.search_tweets(query=[(simone + 'lang:pt' )] ,
                                            max_results=100,
                                            start_time=inicio,
                                            end_time=fim)

baseLula= baseLula.drop_duplicates()
baseBolsonaro= baseBolsonaro.drop_duplicates()
baseCiro= baseCiro.drop_duplicates()
baseSimone= baseSimone.drop_duplicates()
baseLula.to_csv('extracoes/extracao_' +
                str(dia)+"_"+
                mes.replace("-", "_") + 
                lula.split(" ", 2)[1].replace("(", "") + '.csv')
baseBolsonaro.to_csv('extracoes/extracao_' +
                str(dia)+"_"+
                mes.replace("-", "_") + 
                bolsonaro.split(" ", 2)[1].replace("(", "") + '.csv')
baseCiro.to_csv('extracoes/extracao_' +
                str(dia)+"_"+
                mes.replace("-", "_") + 
                ciro.split(" ", 2)[1].replace("(", "") + '.csv')
baseSimone.to_csv('extracoes/extracao_' +
                str(dia)+"_"+
                mes.replace("-", "_") + 
                simone.split(" ", 2)[1].replace("(", "") + '.csv')